myWebAppLaunchTemplate:
 Type: AWS::EC2::LaunchTemplate
 Properties: 
   LaunchTemplateData:
     UserData:
       Fn::Base64: !Sub |
         #!/bin/bash
         apt-get update -y
         apt-get install apache2 -y
         systemctl start apache2.service
         cd /var/www/html
         echo "Udacity Demo Web Server Up and Running!" > index.html
     ImageId: ami-005bdb005fb00e791
     KeyName: VocareumKey2
     SecurityGroupIds:
       - sg-020ac9d8f54335c66
     InstanceType: t3.small
     BlockDeviceMappings:
     - DeviceName: "/dev/sdk"
       Ebs:
         VolumeSize: '10'
