# Latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# This triggers a CI pipeline build
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  save-hello-world-output:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "print hello world!"
          command: echo "hello world!" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print-output-file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
        at: ~/
      - run:
        cat ~/output.txt
workflows:
  hello-output:
    jobs:
      - save-hello-world-output
