version: 2.1

commands:
  print_pipeline_id:
    description: "prints the circleCI workflow ID to console"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID} 
jobs:
  output-workflow-id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id
         
workflows:
  build-output:
    jobs:
      - output-workflow-id
