property1: value1
property2: value2

# Given a dictionary with the property name and value apple. additional properties to the dictionary.
name: apple
color: red
weight: 90g

# A dictionary employee is given. Add the remaining properties to it using information from the table below.
employee:
    name: john
    gender: male
    age: 24
    
# Now try adding the address information. Note the address is a dictionary
employee:
    name: john
    gender: male
    age: 24
    address:
        city: edison
        state: new jersey
        country: united states
        
# Given an list/array of apples. Add a new apple to the list to make it a total of 4.
- apple
- apple
- apple
- apple

