property1: value1
property2: value2

# Given a dictionary with the property name and value apple. additional properties to the dictionary.
name: apple
color: red
weight: 90g

# A dictionary employee is given. Add the remaining properties to it using information from the table below.
employee:
    name: john
    gender: male
    age: 24
