---
  - name: "Challenge practice"
    hosts: localhost

    tasks:

      - name: "test reachability"
        ping:

      - name: "find module"
        find:
          path: ~/Users/abraham-bormate/documents/DevOps/ansible
          file_type: file
