# Example list of packages that need to be installed

---
- name: Install softwares
  hosts: all
  vars:
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      
